refactor(netcdf): sync data, revise logger and exceptions
modflowpy/flopy pull request #1230
Opened 2021-09-08 04:29 UTC by mwtoews

This PR refactors several things:

- Use [netCDF4's `sync()` method](https://unidata.github.io/netcdf4-python/#Dataset.sync) to write data to disk, which should avoid "NetCDF: Unknown file format" issues. This should be added at the end of methods that modify the netCDF file.
- Logger messages should now print one per line (using `print(..., end="")`, because the message already has `\n`)
- `NetCDF.__init__` should raise `ImportError` if python-dateutil is not installed, rather than print a message.
- Remove `_dt_str` private method, as it's only used once; rewrite to use [strftime format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)
- Show exceptions to logger messages, or [chain](https://docs.python.org/3/tutorial/errors.html#exception-chaining) them (where appropriate)
- Add context manager feature to NetCdf class, so it can be used in a with statement. This is because it returns an open dataset, which can be written/closed outside the with statement.

2021-09-28 22:05 UTC, mwtoews commented
Any hesitation in a review? The key change is that netCDF files can be written and more safely opened with the data already written, rather than seeing a "NetCDF: Unknown file format" error.

Also, I'm ignoring the Codacy issues, all with code [C0103](http://pylint-messages.wikidot.com/messages:c0103), which generally means variables should be at least 3 characters:

- `dt`, `t` and `t0` are fine names for variables related to time
- `s` was kept as it was before, rather than renaming each instance

2021-10-05 18:46 UTC, jdhughes-usgs requested changes

2021-10-05 19:37 UTC, mwtoews commented on flopy/export/netcdf.py
> +        import netCDF4
I initially removed a try/except here as this method should only be available for an existing NetCdf object created via `__init__` / `initialize_file`, but it's fine to have this here too, so I've re-added it.

2021-10-05 19:58 UTC, jdhughes-usgs commented on flopy/export/netcdf.py
> +        import netCDF4
@mwtoews have you worked with conda-forge recipes? The [conda-forge recipe](https://github.com/conda-forge/flopy-feedstock) for flopy was set up by someone else and I haven't really made any modifications except those needed to create a new release. 

It seems we could add all of the optional flopy dependencies as `run_constrained` entries in the `requirements` section of https://github.com/conda-forge/flopy-feedstock/blob/master/recipe/meta.yaml and avoid some of the `try` `except` wrapping we are doing now. 

Any thoughts?

2021-10-05 22:13 UTC, jdhughes-usgs commented on flopy/export/netcdf.py
> +        import netCDF4
I do like the [import_optional_dependency("netCDF4")](https://github.com/pandas-dev/pandas/blob/65998341034861527517756e6dd134dafea2b766/pandas/compat/_optional.py#L64) in pandas. @langevin-usgs and I talked about doing something like this. I will try and implement something like this before the next version (unless this is something you would like to implement).

2021-10-05 22:43 UTC, merged